#baseURL = 'https://luca-mancini.gitlab.io/site-lucamancini/'
baseURL = 'https://www.example.com'
languageCode = 'en-us'
title = 'Luca Mancini'
disableKinds = ["taxonomy", "term"]

[params]
    author = 'Luca Mancini'